# Azure Container App Configuration
# This file defines the deployment configuration for Azure Container Apps

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-bus-event-generator
  labels:
    app: service-bus-event-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-bus-event-generator
  template:
    metadata:
      labels:
        app: service-bus-event-generator
    spec:
      containers:
      - name: service-bus-event-generator
        image: your-registry.azurecr.io/service-bus-event-generator:latest
        ports:
        - containerPort: 8000
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: LOG_LEVEL
          value: "info"
        - name: ENVIRONMENT
          value: "production"
        - name: USE_MANAGED_IDENTITY
          value: "true"
        - name: SERVICE_BUS_NAMESPACE
          valueFrom:
            secretKeyRef:
              name: service-bus-secrets
              key: namespace
        - name: SERVICE_BUS_QUEUE_NAME
          value: "events"
        - name: SERVICE_BUS_TOPIC_NAME
          value: ""  # Leave empty to use queue instead of topic
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-bus-event-generator-service
spec:
  selector:
    app: service-bus-event-generator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
